curl -X 'POST' \
  'http://localhost:5090/api/Extraction/process' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -d '{
  "emails": [
    "Hi Patricia, Please create an expense claim for the below. Relevant details are marked up as requested... <expense><cost_centre>DEV632</cost_centre><total>35,000</total><payment_method>personal card</payment_method></expense> From: William Steele",

    "Hi Maria, Please create a reservation for 10 at the at 7.30pm. <vendor>Seaside Steakhouse</vendor> for our <description>development team’s project end celebration</description> on <date>27 April 2022</date> at 7.30pm Regards, William"
  ]
}'